services:
  pong:
    build:
      context: .
      args:
        - BASE=${BASE:-/pong}
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    # environment:
    #   - PORT=3000
    #   - HOST=0.0.0.0
    #   - SEED=99999
